# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c683790c4e6a28bc2661631a40b73587"
application_url = "https://scenarios-energy-msgid-long.trycloudflare.com"
embedded = true
name = "boa-home-task-bv"
handle = "boa-home-task-bv"

[build]
include_config_on_deploy = true
dev_store_url = "home-assignment-113.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://scenarios-energy-msgid-long.trycloudflare.com/auth/callback",
  "https://scenarios-energy-msgid-long.trycloudflare.com/auth/shopify/callback",
  "https://scenarios-energy-msgid-long.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
